CREATE SCHEMA IF NOT EXISTS ewm_events;

CREATE TABLE IF NOT EXISTS ewm_events.categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ewm_events.locations(
    id  BIGSERIAL PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS ewm_events.events(
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    annotation TEXT,
    description TEXT,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    paid BOOLEAN DEFAULT false,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN DEFAULT true,
    state TEXT NOT NULL,

    CONSTRAINT fk_events_categories
        FOREIGN KEY(category_id) REFERENCES ewm_events.categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_events_locations
        FOREIGN KEY(location_id) REFERENCES ewm_events.locations(id)
);

CREATE TABLE IF NOT EXISTS ewm_events.comments(
    id BIGSERIAL PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment_text VARCHAR(512),
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(32) NOT NULL,

    CONSTRAINT fk_comments_events
        FOREIGN KEY(event_id) REFERENCES ewm_events.events(id)
);