CREATE SCHEMA IF NOT EXISTS ewm_compilations;

CREATE TABLE IF NOT EXISTS ewm_compilations.compilations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN DEFAULT false,
    title TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ewm_compilations.compilation_event(
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_compilation_evet PRIMARY KEY (compilation_id, event_id)
);

