server:
  port: 0

spring:
  output:
    ansi:
      enabled: ALWAYS

  application:
    name: aggregator

  kafka:
    producer:
      value-serializer: ru.practicum.ewm.stats.kafka.serializer.AvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: aggregator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.ewm.stats.kafka.deserializer.UserActionAvroDeserializer

aggregator:
  kafka:
    topic:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1
      
  recommendations:
    action-weights:
      VIEW: 0.4
      REGISTER: 0.8
      LIKE: 1.0