CREATE SCHEMA IF NOT EXISTS ewm;

CREATE TABLE IF NOT EXISTS ewm.categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ewm.users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ewm.locations(
    id  BIGSERIAL PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS ewm.events(
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    annotation TEXT,
    description TEXT,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    paid BOOLEAN DEFAULT false,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN DEFAULT true,
    state TEXT NOT NULL,

    CONSTRAINT fk_events_categories
        FOREIGN KEY(category_id) REFERENCES ewm.categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_events_users
        FOREIGN KEY(initiator_id) REFERENCES ewm.users(id),
    CONSTRAINT fk_events_locations
        FOREIGN KEY(location_id) REFERENCES ewm.locations(id)
);

CREATE TABLE IF NOT EXISTS ewm.compilations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN DEFAULT false,
    title TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ewm.compilation_event(
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_compilation_evet PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_event_compilation FOREIGN KEY(compilation_id) REFERENCES ewm.compilations(id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_event_event FOREIGN KEY(event_id) REFERENCES ewm.events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ewm.requests(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,

    CONSTRAINT fk_requests_events FOREIGN KEY(event_id) REFERENCES ewm.events(id),
    CONSTRAINT fk_requests_users FOREIGN KEY(requester_id) REFERENCES ewm.users(id)
);

CREATE TABLE IF NOT EXISTS ewm.comments(
    id BIGSERIAL PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment_text VARCHAR(512),
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(32) NOT NULL,

    CONSTRAINT fk_comments_events
        FOREIGN KEY(event_id) REFERENCES ewm.events(id),
    CONSTRAINT fk_comments_users
        FOREIGN KEY(user_id) REFERENCES ewm.users(id)
);