CREATE SCHEMA IF NOT EXISTS ewm_analyzer;

CREATE TABLE IF NOT EXISTS ewm_analyzer.event_similarity(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_aid BIGINT NOT NULL,
    event_bid BIGINT NOT NULL,
    score DOUBLE PRECISION,
    CONSTRAINT unique_events UNIQUE (event_aid, event_bid)
);

CREATE TABLE IF NOT EXISTS ewm_analyzer.user_action(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    weight DOUBLE PRECISION,
    action_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
)